Store/StoreApp/Areas/Admin/Controllers/ProductController.cs
using Entities.Dtos;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }
        public IActionResult Create()
        {
            ViewBag.Categories = GetCategoriesSelectList();

            return View();
        }

        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetAllCategory(false), "CategoryID", "CategoryName", "1");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([FromForm] ProductDtoForInsertion productDto, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                //file operation
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                productDto.ImageUrl = String.Concat("/images/", file.FileName);
                _manager.ProductService.CreateProduct(productDto);
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Update([FromRoute(Name = "id")] int id)
        {
            ViewBag.Categories = GetCategoriesSelectList();
            var model = _manager.ProductService.GetOneProductForUpdate(id, false);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] ProductDtoForUpdate productDto, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                productDto.ImageUrl = String.Concat("/images/", file.FileName);
                _manager.ProductService.UpdateOneProduct(productDto);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete([FromRoute(Name = "id")] int id)
        {
            _manager.ProductService.DeleteOneProduct(id);

            return RedirectToAction("Index");
        }
    }
}

Store/StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetAllCategory(false);
            return View(categories);
        }
    }
}

Store/StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
     
       
    }
}

Store/StoreApp/Views/Product/Get.cshtml
@model Product

<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <h6 class="display-6">
                @Model.ProductName
            </h6>

            <img class="img-fuild shadow rounded-3 my-3" width="250" src="@Model?.ImageUrl" alt="@Model.ProductName">
            <p class="my-3">@Model.Summary</p>
            <p class="lead text-danger my-3">@Model.Price.ToString("c")</p>

            <div class="btn-group my-3">
                <a class="btn btn-primary" asp-controller="Home" asp-action="Index">
                    <i class="fa-solid fa-house"></i>
                    Home</a>
                <a class="btn btn-primary" asp-controller="Product" asp-action="Index">
                    <i class="fa-solid fa-shop"></i>
                    Product</a>
            </div>
        </div>
    </div>
</div>

Store/StoreApp/Views/Product/Index.cshtml
@model IQueryable<Product>
@section Footer {
    <div>
        <p style="text-align:center;">Umutcan Gülher</p>
    </div>
}


<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoriesMenu")
    </div>
    <div class="col-md-9">
        <div class="row my-2">
            @foreach (Product prd in Model)
            {

                <partial name="_ProductCard" model="@prd" />

            }
        </div>
    </div>

</div>

Store/StoreApp/Views/Product/_ProductCard.cshtml
@model Product



<div class="col-sm-12 col-md-4 my-3">
    <div class="card" style="width: 18rem;">
        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.ProductName</h5>
            <p class="card-text">@Model.Price.ToString("c")</p>
            <div class="btn btn-group">
            <a class="btn btn-primary mx-1" asp-action="Get" asp-route-id="@Model.ProductID">
                <i class="fa-solid fa-arrow-right"></i>
                 Details</a>
            
            <form id="@Model.ProductID" asp-page="/Cart" method="post">
            <input type="hidden" asp-for="ProductID">
            <input type="hidden" name="returnUrl" value="/Product/Get/@Model.ProductID">
                <button type="submit" class="btn btn-outline-primary">
                    <i class="fa fa-cart-plus"></i>
                </button>
            </form>

        </div>
        </div>
    </div>
</div>