Store/StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructe.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager _manager;


        public Cart Cart { get; set; } // IoC
        public CartModel(IServiceManager manager , Cart cartService)
        {
            _manager = manager;
            Cart = cartService;
        }

        public string ReturnUrl { get; set; } = "/";

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }
        public IActionResult OnPost(int productId, string returnUrl)
        {
            Product? product = _manager.ProductService.GetOneProduct(productId, false);

            if (product is not null)
            {
                // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
                Cart.AddItem(product, 1);
               // HttpContext.Session.SetJson<Cart>("cart",Cart);
            }
            return Page(); // returnUrl
        }

        public IActionResult OnPostRemove(int id, string returnUrl)
        {
            //Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.ProductID.Equals(id)).Product);
            //HttpContext.Session.SetJson<Cart>("cart", Cart);
            return Page();
        }

    }

}

Store/StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreApp.Infrastructe.Extensions;

namespace StoreApp.Pages
{
    public class DemoModel : PageModel
    {
        public String? FullName => HttpContext?.Session?.GetString("name") ?? "...";

       
        public void OnGet()
        {

        }
        public void OnPost([FromForm] string name)
        {
            // FullName = name;
            HttpContext.Session.SetString("name", name);
            
        }
    }
}

Store/StoreApp/Pages/Cart.cshtml
@page "/sepet"
@model CartModel

<div>
    <div class="text-center display-6">
        Cart
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
            {
                <tr>
                    <th>@line.Product.ProductName</th>
                    <th>@line.Quantity</th>
                    <th>@line.Product.Price.ToString("c")</th>
                    <th>@((line.Product.Price * line.Quantity).ToString("c2"))</th>
                    <th>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@line.Product.ProductID">
                             <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                             <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                                Remove 
                            </button>
                        </form>
                    </th>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-right">Total : </td>
                <td class="text-right text-danger">
                    @Model.Cart?.ComputeTotalValue().ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>
</div>

Store/StoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center  my-5" style="border: solid red 2px;">
    <div class="display-6">Contact</div>
    <div class="lead">
        <i class="fa fa-phone"></i>
        <p>
            Alo 180 Btk AKADEMi bilgi ve destek hatti
        </p>
        <i class="fa-solid fa-address-book"></i>
        <p>
            Eskişehir/Odunpazari Emek mh. 
        </p>
        <i class="fa-solid fa-envelope"></i>
        <p>
            destek@btkakademi.gov.tr
        </p>
    </div>
</div>

Store/StoreApp/Pages/Demo.cshtml
@page
@model DemoModel

<div class="my-5 text-center">
    <form method="post" asp-page="/Demo">
    <div class="display-6">Hello , @Model?.FullName</div>
    <div class="form-group">
        <input class="form-control" name="name" placeholder="Enter Your Name">
        <input type="submit" class="btn btn-primary my-3">
    </div>
    </form>
</div>